FROM python:3.13-slim

WORKDIR /srv/app

# Минимальные зависимости
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /srv/app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Устанавливаем зависимости только для listener
RUN pip install --no-cache-dir aiohttp

# Запускаем listener
CMD ["python", "src/surguard_listener.py"]